#!/bin/sh

set -eu

OLEVELS='0 1 2 3 s'
FILES=$( ls *.c )
BITS="32 64"

for B in $BITS; do
    for O in $OLEVELS; do
        for F in $FILES; do
            echo "gcc -m$B -O$O -S $F -o ${F%.c}-gcc-x86-$B-O${O}.s"
            gcc -m$B -O$O -S $F -o ${F%.c}-gcc-x86-$B-O${O}.s
        done
    done
done

if which arm-none-eabi-gcc >/dev/null; then
    for A in armv6 armv6-m armv7-m armv7-a armv8-a; do
        case $A in
            *-m)    T=-mthumb ;;
            *)      T='' ;;
        esac
        for O in $OLEVELS; do
            for F in $FILES; do
                echo "arm-none-eabi-gcc -march=$A $T -O$O -S $F -o ${F%.c}-gcc-$A-O${O}.s"
                arm-none-eabi-gcc -march=$A $T -O$O -S $F -o ${F%.c}-gcc-$A-O${O}.s
            done
        done
    done
fi
