#!/bin/sh

set -eu

OLEVELS='0 1 2 3 s'
FILES=$( ls *.c )
BITS="32 64"

for B in $BITS; do
    for O in $OLEVELS; do
        for F in $FILES; do
            echo "gcc -m$B -O$O -S $F -o ${F%.c}-gcc-x86-$B-O${O}.s"
            gcc -m$B -O$O -S $F -o ${F%.c}-gcc-x86-$B-O${O}.s
        done
    done
done

